sampleData= [
    {
    title: "Animal 2023 WEB-DL Hindi Full Movie Download 1080p 720p 480p",
    url: "animal-hindi-full-movie-download-hdts",
    description: "Animal 2023 WEB-DL Hindi Full Movie Download 1080p, 720p & 480p. Animal 2023 This is a Bollywood Movie and available in Hindi 1080p, 720p & 480p qualities. This is one of the best movies based on Action, Crime, Drama. Animal 2023 WEB-DL Hindi Movie is also Available in Bollywood 300Mb Movies and Bollywood 720p Movies Only on Tolly4u.",
    originalTitle: "Animal",
    story: "An action-crime-drama about a ruthless gangster who is hunted by a cop and a rival, while trying to protect his family from his dark past.",
    genre: "Action, Drama",
    category: "Bollywood",
    categoryType: "Action",
    directors: "Sandeep Reddy Vanga",
    casts: "Ranbir Kapoor, Anil Kapoor, Rashmika Mandanna, Bobby Deol",
    runtime: "160 minutes",
    releaseDate: "1 December 2023",
    filmPoster: "https://upload.wikimedia.org/wikipedia/en/thumb/9/90/Animal_%282023_film%29_poster.jpg/220px-Animal_%282023_film%29_poster.jpg",
    screenshoots: ["https://imgbb.top/ib/iGsYvebQ5JasX0b_1717237937.jpg","https://imgbb.top/ib/xmpWCp5br87HnUk_1717237938.jpg","https://imgbb.top/ib/Su0NzSZxlOKn2an_1717237938.jpg","https://imgbb.top/ib/ePjW1aTDzXkxBTh_1717237938.jpg","https://imgbb.top/ib/44Ldfyp7Y1A9CWf_1717237938.jpg"],
    videoSrc: "https://short.ink/IMR0VCPbdWX",
    videoDownload1: "https://photojin.homes/download/b4agNx8XDPs",
    videoDownload2: "https://photojin.homes/download/b4agNx8XDPs",
    videoDownload3: "https://bolly4u.today/?fba613d643=dTFBMlB1SXdDZHZWTjVMZm9xMXduSHJ4V3doR05mV1AvY3psY3Q5ejhZSml2NityemxDVTMvelh4VHRHR1hZYmlBTTVXNmM5TzRaKzRlYmI1aWxHMHRjbkVaMEg1MHlKMW0vc3V0cGU4Lzg9",
  },
  {
    "title": "The Archies Full movie download 1080p",
    "url": "the-archies-2023-hindi-full-movie-download-webrip",
    "description": "The Archies 2023 WEB-DL Hindi Full Movie Download 1080p, 720p & 480p. The Archies 2023 This is a Bollywood Movie and available in Hindi 1080p, 720p & 480p qualities. This is one of the best movies based on Comedy, Drama, Musical. The Archies 2023 WEB-DL Hindi Movie is also Available in Bollywood 300Mb Movies and Bollywood 720p Movies Only on Tolly4u.",
    "originalTitle": "The Archies",
    "story": "A musical-comedy about a group of college students who form a band and compete in a music contest, while dealing with their personal and romantic issues.",
    "genre": "Comedy",
    "category": "Bollywood",
    "categoryType": "Action",
    "casts": "Mihir Ahuja, Dot, Khushi Kapoor, Suhana Khan",
    "directors": "Zoya Akhtar",
    "runtime": "130 minutes",
    "releaseDate": "7 December 2023",
    "filmPoster": "https://upload.wikimedia.org/wikipedia/en/thumb/4/45/The_Archies_film_poster.jpg/220px-The_Archies_film_poster.jpg",
    "videoSrc": "https://short.ink/lezhHmRCQG",
    "videoDownload1": "https://photojin.homes/download/31NFSFdm5D2",
    "videoDownload3": "https://photojin.homes/download/31NFSFdm5D2",
    "videoDownload2": "https://bolly4u.today/?fba613d643=VHRWOFRNSUhtMDZxdXlPMk9ERXdYMCtEZzlheHFEZ2FnRUdGN3pCd3dPak1ZOXFHSTZ2TlZ1d0hWVXk3ZTFCRlc3NUw5TmRrRUVIbWN6dTNpM2hXV1llNDR0bnpWaGR2dUkycHJNZWJPdWs9",
  },
  {
    "title": "web series",
    "url": "web-series",
    "description": "The Archies 2023 WEB-DL Hindi Full Movie Download 1080p, 720p & 480p. The Archies 2023 This is a Bollywood Movie and available in Hindi 1080p, 720p & 480p qualities. This is one of the best movies based on Comedy, Drama, Musical. The Archies 2023 WEB-DL Hindi Movie is also Available in Bollywood 300Mb Movies and Bollywood 720p Movies Only on Tolly4u.",
    "originalTitle": "web series",
    "story": "A musical-comedy about a group of college students who form a band and compete in a music contest, while dealing with their personal and romantic issues.",
    "genre": "Comedy",
    "category": "Web Series",
    "categoryType": "Action",
    "casts": "Mihir Ahuja, Dot, Khushi Kapoor, Suhana Khan",
    "directors": "Zoya Akhtar",
    "runtime": "130 minutes",
    "releaseDate": "7 December 2023",
    "screenshoots": ["https://imgbb.top/ib/iGsYvebQ5JasX0b_1717237937.jpg","https://imgbb.top/ib/xmpWCp5br87HnUk_1717237938.jpg","https://imgbb.top/ib/Su0NzSZxlOKn2an_1717237938.jpg","https://imgbb.top/ib/ePjW1aTDzXkxBTh_1717237938.jpg","https://imgbb.top/ib/44Ldfyp7Y1A9CWf_1717237938.jpg"],
    "filmPoster": "https://upload.wikimedia.org/wikipedia/en/thumb/4/45/The_Archies_film_poster.jpg/220px-The_Archies_film_poster.jpg",
    "videoSrc": "https://short.ink/lezhHmRCQG",
    "episodes": ["https://photojin.homes/download/31NFSFdm5D2","https://photojin.homes/download/31NFSFdm5D2","https://photojin.homes/download/31NFSFdm5D2","https://photojin.homes/download/31NFSFdm5D2","https://photojin.homes/download/31NFSFdm5D2",],
    "videoDownload1": "https://photojin.homes/download/31NFSFdm5D2",
    "videoDownload3": "https://photojin.homes/download/31NFSFdm5D2",
    "videoDownload2": "https://bolly4u.today/?fba613d643=VHRWOFRNSUhtMDZxdXlPMk9ERXdYMCtEZzlheHFEZ2FnRUdGN3pCd3dPak1ZOXFHSTZ2TlZ1d0hWVXk3ZTFCRlc3NUw5TmRrRUVIbWN6dTNpM2hXV1llNDR0bnpWaGR2dUkycHJNZWJPdWs9",
  },
  {
    "title": "12th Fail 2023 Hindi Full Movie Download 1080p",
    "url": "12th-fail-2023-hindi-full-movie-download-webrip",
    "description": "12th Fail 2023 WEB-DL Hindi Full Movie Download 1080p, 720p & 480p. 12th Fail 2023 This is a Bollywood Movie and available in Hindi 1080p, 720p & 480p qualities. This is one of the best movies based on Drama. 12th Fail 2023 WEB-DL Hindi Movie is also Available in Bollywood 300Mb Movies and Bollywood 720p Movies Only on Tolly4u.",
    "originalTitle": "12th Fail",
    "story": "The real-life story of IPS Officer Manoj Kumar Sharma and IRS Officer Shraddha Joshi.",
    "genre": "Drama",
    "category": "Bollywood",
    "categoryType": "Romance",
    "casts": "Vikrant Massey, Priyanshu Chatterjee, Medha Shankar",
    "directors": "Vidhu Vinod Chopra",
    "runtime": "146 min",
    "releaseDate": "27 October 2023",
    "screenshoots": ["https://imgbb.top/ib/iGsYvebQ5JasX0b_1717237937.jpg","https://imgbb.top/ib/xmpWCp5br87HnUk_1717237938.jpg","https://imgbb.top/ib/Su0NzSZxlOKn2an_1717237938.jpg","https://imgbb.top/ib/ePjW1aTDzXkxBTh_1717237938.jpg","https://imgbb.top/ib/44Ldfyp7Y1A9CWf_1717237938.jpg"],
    "filmPoster": "https://myimg.click/images/2023/12/29/oie_29611564G4KFBN2.jpg",
    "videoSrc": "https://short.ink/tjoS8It9bp",
    "fileSizes": ["2.8GB","1.3GB", "712MB"],
    "videoDownload1": "https://photojin.homes/download/Bb9QY8gprHL",
    "videoDownload3": "https://photojin.homes/download/Bb9QY8gprHL",
    "videoDownload2": "https://bolly4u.today/?fba613d643=ODFLejZtN1lBbGZ6YVdWeTdSRERrRFZrNy83SVdrZStvN3doVW9JdGpJT0ZtN2NNWjhLU1RjUnN2L0IzSGFLc09jYUFvMWNvYkM2VzJoRDRuakMwbGNCeU5haUpnVWVibGlaQzc0K2RINWc9",
  },
  {
    "title": "Mission Raniganj 2023 Hindi Full Movie Download 1080p",
    "url": "mission-raniganj-2023-hindi-full-movie-download-webrip",
    "description": "Mission Raniganj 2023 WEB-DL Hindi Full Movie Download 1080p, 720p & 480p. Mission Raniganj 2023 This is a Bollywood Movie and available in Hindi 1080p, 720p & 480p qualities. This is one of the best movies based on Drama. Mission Raniganj 2023 WEB-DL Hindi Movie is also Available in Bollywood 300Mb Movies and Bollywood 720p Movies Only on Tolly4u.",
    "originalTitle": "Mission Raniganj",
    "story": "A total of 65 miners were trapped in a mine, who were rescued by mining engineer Jaswant Singh Gill.",
    "genre": "Action, Biography",
    "category": "Bollywood",
    "categoryType": "Action",
    "casts": "Akshay Kumar, Parineeti Chopra, Rajesh Sharma",
    "directors": "Tinu Suresh Desai, Tinu Suresh Desai",
    "runtime": "135 min",
    "releaseDate": "6 Oct 2023",
    "filmPoster": "https://myimg.click/images/2023/12/01/Mission-Raniganj-2023.jpg",
    "videoSrc": "https://short.ink/3kfv1LxtgzJ",
  },
  {
    "title": "Safed 2023 Hindi Full Movie Download 1080p",
    "url": "safed-2023-hindi-full-movie-download-webrip",
    "description": "Safed 2023 WEB-DL Hindi Full Movie Download 1080p, 720p & 480p. Safed 2023 This is a Bollywood Movie and available in Hindi 1080p, 720p & 480p qualities. This is one of the best movies based on Drama. Safed 2023 WEB-DL Hindi Movie is also Available in Bollywood 300Mb Movies and Bollywood 720p Movies Only on  Tolly4u.",
    "originalTitle": "Safed",
    "story": "Throws light into the dark world of a widow and a eunuch who, isolated and abandoned by society, finding solace in each other.",
    "genre": "Drama",
    "category": "Bollywood",
    "categoryType": "Romance",
    "casts": "Meera Chopra, Barkha Bisht, Abhay Verma",
    "directors": "Sandeep Singh",
    "runtime": "90 min",
    "releaseDate": "29 December 2023",
    "filmPoster": "https://myimg.click/images/2023/12/29/Safed-2023.jpg",
    "screenshoots": ["https://imgbb.top/ib/iGsYvebQ5JasX0b_1717237937.jpg","https://imgbb.top/ib/xmpWCp5br87HnUk_1717237938.jpg","https://imgbb.top/ib/Su0NzSZxlOKn2an_1717237938.jpg","https://imgbb.top/ib/ePjW1aTDzXkxBTh_1717237938.jpg","https://imgbb.top/ib/44Ldfyp7Y1A9CWf_1717237938.jpg"],
    "videoSrc": "https://short.ink/JoSBDKMn3c",
    "links1080p": ["https://photojin.homes/download/Bb9QY8gprHL", "https://www.tolly4u.site", "https://google.com", "https://youtube.com"],
    "links480p": ["https://www.tolly4u.site", "https://google.com", "https://youtube.com"],
    "links720p": ["https://google.com", "https://youtube.com"],
    "fileSizes": ["2.9GB", "1.5GB", "659MB"],
  }
];

module.exports = {data: sampleData}